name: Run linters on PRs

on:
  pull_request:
    branches:
      - development
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      # Use the Ruff linter to annotate code style / best-practice issues
      # NOTE: More config provided in pyproject.toml
      - name: Lint and annotate PR
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
